#!/bin/bash

# pushを確認するブランチ

# subtreeディレクトリ配下を探し、そこに変更があった場合、エラーを返す
readonly MASTER='master'
readonly DEVELOP='develop'

echo 'pre-push start'

### 条件 ###
# develop/masterへのpushかどうか
# subtree配下のファイルに変更があるかどうか

while read local_ref local_sha remote_ref remote_sha
do
  if [ "${remote_ref##refs/heads/}" = $MASTER ] || [ "${remote_ref##refs/heads/}" = $DEVELOP ]; then
    echo 'you will push to remote master or develop branch'
  else
    echo 'nothing to do'
  fi
done

# git push origin topic
# git subtree split --prefix ModuleA --onto subtree/module_a/master -b subtree/module_a/topic
# git checkout subtree/module_a/topic
# git push module_a subtree/module_a/topic:topic

# subtreeに上記の変更を適用させる
# git pull origin master --prune
# git branch -d topic
# git checkout subtree/module_a/master
# git pull module_a master:subtree/module_a/master
# git merge subtree/module_a/topic
# git push module_a subtree/module_a/master:master
# git branch -d subtree/module_a/topic
# git push module_a :topic

echo 'pre-push finish'